version: '3.8'

name: onplay

services:
  nginx:
    build: ./nginx
    ports:
      - "9090:80"
    volumes:
      - ./media:/var/www/media:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - api
      - frontend
    restart: unless-stopped

  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://mediauser:mediapass@postgres:5432/mediadb
      - REDIS_URL=redis://redis:6379/0
      - MEDIA_ROOT=/media
      - CORS_ORIGINS=http://localhost:9090,http://localhost:5173
    volumes:
      - ./backend:/app
      - ./media:/media
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  worker:
    build: ./backend
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2
    environment:
      - DATABASE_URL=postgresql://mediauser:mediapass@postgres:5432/mediadb
      - REDIS_URL=redis://redis:6379/0
      - MEDIA_ROOT=/media
    volumes:
      - ./backend:/app
      - ./media:/media
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    deploy:
      replicas: 2

  beat:
    build: ./backend
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://mediauser:mediapass@postgres:5432/mediadb
      - REDIS_URL=redis://redis:6379/0
      - MEDIA_ROOT=/media
    volumes:
      - ./backend:/app
      - ./media:/media
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:9090/api
      - VITE_WS_URL=ws://localhost:9090/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=mediadb
      - POSTGRES_USER=mediauser
      - POSTGRES_PASSWORD=mediapass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  nginx_logs:
